#
#
#	40<mw<150 (signal region)
#
#
#python make_aQGC_plots.py -n  /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root    --grid -v PuppiAK8_jet_mass_so --leg "tW-ch"  --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*(((type==1) || (type==0)) && (l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && ((PuppiAK8_jet_mass_so>65) && (PuppiAK8_jet_mass_so<85)) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000) )" --ymax 15
#python make_aQGC_plots.py -n  /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root  /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_s_channel.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_antitop_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_antitop.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_top_4f.root  --grid -v PuppiAK8_jet_mass_so --leg "tW-ch" "s-ch" "tW-ch: tbar" "t-ch: tbar" "t-ch" --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*(((type==1) || (type==0)) && (l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && ((PuppiAK8_jet_mass_so>40) && (PuppiAK8_jet_mass_so<150)) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000) )" --ymax 15
#
#
#	65<mw<105 (signal region)
#
#
python make_aQGC_plots.py -n /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_s_channel.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_antitop_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_antitop.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_top_4f.root  --grid -v PuppiAK8_jet_mass_so --leg "s-ch" "tW-ch: tbar" "tW-ch" "t-ch: tbar" "t-ch" --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*btag0Wgt*((l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && ((PuppiAK8_jet_mass_so>65) && (PuppiAK8_jet_mass_so<85)) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000))" --ymax 25
#
#
#	lower side band + upper side band
#
#
#python make_aQGC_plots.py -n /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_s_channel.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_antitop_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_antitop.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_top_4f.root  --grid -v PuppiAK8_jet_mass_so --leg "s-ch" "tW-ch: tbar" "tW-ch" "t-ch: tbar" "t-ch" --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*(((type==1) || (type==0)) && (l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && (((PuppiAK8_jet_mass_so>40) && (PuppiAK8_jet_mass_so<65))|| ((PuppiAK8_jet_mass_so>105) && (PuppiAK8_jet_mass_so<150))) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000))" --ymax 25
#
#
#	lower side band
#
#
#python make_aQGC_plots.py -n /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_s_channel.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_antitop_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_antitop.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_top_4f.root  --grid -v PuppiAK8_jet_mass_so --leg "s-ch" "tW-ch: tbar" "tW-ch" "t-ch: tbar" "t-ch" --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*(((type==1) || (type==0)) && (l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && (((PuppiAK8_jet_mass_so>40) && (PuppiAK8_jet_mass_so<65))) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000))" --ymax 25
#
#
#	upper side band
#
#
#python make_aQGC_plots.py -n /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_s_channel.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_antitop_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_tW_top_5f_NoFullyHadronicDecays.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_antitop.root /eos/uscms/store/user/rasharma/SecondStep/WWTree_2018_01_07_12h02/HaddedFiles/ST_t_channel_top_4f.root  --grid -v PuppiAK8_jet_mass_so --leg "s-ch" "tW-ch: tbar" "tW-ch" "t-ch: tbar" "t-ch" --xmin 40 --xmax 150 --xlabel "mW invariant mass"  -o mW_mass.png --legPos "tl"  --nbin 11 --cut "wSampleWeight*35867.1*genWeight*trig_eff_Weight*id_eff_Weight*pu_Weight*(((type==1) || (type==0)) && (l_pt2<0) && ((l_pt1>30.) && (abs(l_eta1)<2.5)) && ((ungroomed_PuppiAK8_jet_pt>200)&&(abs(ungroomed_PuppiAK8_jet_eta)<2.4)) && ((vbf_maxpt_j1_pt>30) && (vbf_maxpt_j2_pt>30)) && (vbf_maxpt_jj_m>500) && (nBTagJet_loose==0) && (pfMET_Corr>50) && ((PuppiAK8_jet_tau2tau1<0.55)) && (((PuppiAK8_jet_mass_so>105) && (PuppiAK8_jet_mass_so<150))) && (abs(vbf_maxpt_j2_eta-vbf_maxpt_j1_eta)>4.0) && (vbf_maxpt_jj_m>800) && (BosonCentrality_type0>1.0) && (abs(ZeppenfeldWL_type0/vbf_maxpt_jj_Deta)<0.3) && (abs(ZeppenfeldWH/vbf_maxpt_jj_Deta)<0.3) && (mass_lvj_type0>600) && (mass_lvj_type0<4000))" --ymax 25
